### ISSUE TITLE
inconsistent php version constraint

### ISSUE THREAD

**Issue by Mainbird** [ameos/ameos_mailredirect#8]
Hi, can you please update the PHP version constraint inside ext_emconf.php? :)

The current value inside ext_emconf.php does not match the constraint inside composer.json.

ext_emconf.php
`'php'   => '5.5.0-7.3.99'`

composer.json
`"php": ">=7.0.0"`

Thank you in advance :)

**Comment by ameos** [comment]
Hello,

Thanks for noticing the issue.
It has been fixed with release 1.2.4

Have a nice day
