### ISSUE TITLE
Not working with form framework and fluid mails

### ISSUE THREAD

**Issue by Mainbird** [ameos/ameos_mailredirect#9]
Hi, currently your extension is not working with form framework email finishers when fluid mails are enabled.

In this case:
https://github.com/TYPO3/typo3/blob/v11.5.10/typo3/sysext/form/Classes/Domain/Finishers/EmailFinisher.php#L194
the send method of the mailer class is called directly, so your provided xclasses will not fire at all.

I am using TYPO3 11.

Is it possible to xclass the Mailer-Class itself? Then maybe your other xclasses are not required anymore. A better approach could also be a PSR-14 event: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Events/Events/Core/Mail/AfterMailerInitializationEvent.html, but this will work only for TYPO3 11+ then.

What do you think?

**Comment by ameos** [comment]
Hello,

Thank you for noticing the issue.

We've juste released version 2.0.0 of the extension.
This new version now supports redirection when using Form framework with FluidEmails.
The version is compatible with TYPO3 >= v10.
